### ISSUE TITLE
TRACKING: First "Real" Release 

### ISSUE THREAD

**Issue by bobmcwhirter** [seedwing-io/seedwing-policy#50]
Things we need to do prior to the first real release:

- [ ] Determine capitalization rules, change if necessary
- [ ] Real-time monitoring of policy evaluation
- [ ] Full CycloneDX well-formedness.
